---
- name: Get existing VMs
  ansible.builtin.shell: >-
    pvesh get /nodes/{{ ansible_facts.hostname }}/qemu --output-format json
  register: existing_vms_response
  changed_when: false

- name: Create templates
  ansible.builtin.include_tasks: create_template.yml
  vars:
    existing_vms: "{{ existing_vms_response.stdout | from_json }}"
  with_items: "{{ templates | default({}) | dict2items }}"
  loop_control:
    loop_var: template
