---
- name: Get ISO images Storage {{ storage_config.key }}
  ansible.builtin.command:
    pvesh get /nodes/{{ ansible_facts.hostname }}/storage/{{ storage_config.key }}/content
    --content iso
    --output-format json
  changed_when: false
  register: existing_iso_files

- name: Update ISO images Storage {{ storage_config.key }}
  vars:
    iso_names: "{{ storage_config.value.isos | map('basename') }}"
    existing_iso_names:
      "{{ existing_iso_files.stdout | from_json | json_query('[].volid') | map('basename') }}"
  block:
    - name: Download ISO images Storage {{ storage_config.key }}
      ansible.builtin.command: >-
        pvesh create /nodes/{{ ansible_facts.hostname }}/storage/{{ storage_config.key }}/download-url
        --content iso
        --filename {{ iso | basename }}
        --url {{ iso }}
      when: iso | basename not in existing_iso_names
      with_items: "{{ storage_config.value.isos }}"
      loop_control:
        loop_var: iso

    - name: Delete ISO images Storage {{ storage_config.key }}
      ansible.builtin.command: >-
        pvesh delete /nodes/{{ ansible_facts.hostname }}/storage/{{ storage_config.key }}/content/{{ iso }}
      when: vm_iso_remove_unreferenced and iso | basename not in iso_names
      with_items: "{{ existing_iso_files.stdout | from_json | json_query('[].volid') }}"
      loop_control:
        loop_var: iso
